"use client";

import { useEffect, useState, useCallback, useMemo } from "react";
import { createClient } from "@/lib/supabase/client";
import type { Employee, Invoice, Distribution } from "@/lib/types";
import { formatUSD, formatPKR, formatNumber, formatMonth } from "@/lib/format";
import {
  Card,
  CardHeader,
  CardTitle,
  CardContent,
} from "@/components/ui/card";
import {
  Table,
  TableHeader,
  TableRow,
  TableHead,
  TableBody,
  TableCell,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { ChevronDown, Printer, Trash2 } from "lucide-react";
import { toast } from "sonner";

type EmployeeForm = {
  name: string;
  cnic: string;
  default_salary_usd: string;
  default_threshold: string;
  default_contractor_tax: string;
  default_remittance_tax: string;
  is_active: boolean;
};

const emptyForm: EmployeeForm = {
  name: "",
  cnic: "",
  default_salary_usd: "",
  default_threshold: "",
  default_contractor_tax: "",
  default_remittance_tax: "",
  is_active: true,
};

function formFromEmployee(emp: Employee): EmployeeForm {
  return {
    name: emp.name,
    cnic: emp.cnic ?? "",
    default_salary_usd: String(emp.default_salary_usd),
    default_threshold: String(emp.default_threshold),
    default_contractor_tax: String(emp.default_contractor_tax),
    default_remittance_tax: String(emp.default_remittance_tax),
    is_active: emp.is_active,
  };
}

type InvoiceWithMonth = Invoice & { reference_month: string };

function printInvoice(inv: InvoiceWithMonth, empName: string) {
  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(`
    <html><head><title>Invoice - ${empName} - ${inv.reference_month}</title>
    <style>
      body { font-family: system-ui, sans-serif; padding: 40px; color: #1a1a1a; max-width: 600px; margin: 0 auto; }
      table { width: 100%; border-collapse: collapse; margin-top: 16px; }
      th, td { padding: 10px 12px; text-align: left; border-bottom: 1px solid #e5e5e5; }
      th { font-size: 13px; color: #666; font-weight: 600; }
      td { font-size: 14px; font-family: monospace; text-align: right; }
      .header { margin-bottom: 24px; }
      .header h1 { font-size: 22px; margin: 0; }
      .header p { color: #666; margin: 4px 0 0; font-size: 14px; }
      .green { color: #059669; }
      .red { color: #dc2626; }
      .net td { font-size: 20px; font-weight: 700; border-top: 2px solid #1a1a1a; }
      .net th { border-top: 2px solid #1a1a1a; font-size: 14px; }
      .footer { margin-top: 40px; font-size: 11px; color: #aaa; }
    </style></head><body>
    <div class="header">
      <h1>Kontemplay Finance</h1>
      <p>Payment Invoice &mdash; ${inv.reference_month}</p>
    </div>
    <table>
      <tr><th>Employee</th><td style="font-family:sans-serif;font-weight:600">${empName}</td></tr>
      <tr><th>Salary (USD)</th><td>$${inv.salary_usd}</td></tr>
      <tr><th>Exchange Rate</th><td>${formatNumber(inv.rate_applied, 2)} PKR/USD</td></tr>
      <tr><th>Gross (PKR)</th><td>${formatPKR(inv.gross_pkr)}</td></tr>
      <tr><th>Contractor Tax (${inv.contractor_tax_percent}%)</th><td class="red">-${formatPKR(inv.contractor_tax_pkr)}</td></tr>
      <tr><th>Remittance Tax (${inv.remittance_tax_percent}%)</th><td class="red">-${formatPKR(inv.remittance_tax_pkr)}</td></tr>
      <tr><th>Total Tax</th><td class="red">-${formatPKR(inv.total_tax_pkr)}</td></tr>
      <tr class="net"><th>Net Payable</th><td class="green">${formatPKR(inv.net_pkr)}</td></tr>
    </table>
    <div class="footer">Generated by Kontemplay Finance on ${new Date().toLocaleDateString("en-PK", { day: "2-digit", month: "long", year: "numeric" })}</div>
    </body></html>
  `);
  w.document.close();
  w.print();
}

export default function EmployeesPage() {
  const supabase = useMemo(() => createClient(), []);
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [loading, setLoading] = useState(true);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<EmployeeForm>(emptyForm);
  const [saving, setSaving] = useState(false);

  // Invoice expansion
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [invoices, setInvoices] = useState<InvoiceWithMonth[]>([]);
  const [loadingInvoices, setLoadingInvoices] = useState(false);

  const fetchEmployees = useCallback(async () => {
    const { data } = await supabase
      .from("employees")
      .select("*")
      .order("name")
      .returns<Employee[]>();
    setEmployees(data ?? []);
    setLoading(false);
  }, [supabase]);

  useEffect(() => {
    fetchEmployees();
  }, [fetchEmployees]);

  async function fetchInvoices(employeeId: string) {
    setLoadingInvoices(true);
    const { data } = await supabase
      .from("invoices")
      .select("*, distributions!inner(reference_month)")
      .eq("employee_id", employeeId)
      .order("created_at", { ascending: false });

    const mapped: InvoiceWithMonth[] = (data ?? []).map((row: Record<string, unknown>) => {
      const dist = row.distributions as { reference_month: string } | null;
      return {
        ...(row as unknown as Invoice),
        reference_month: dist?.reference_month ?? "Unknown",
      };
    });

    setInvoices(mapped);
    setLoadingInvoices(false);
  }

  function toggleExpand(empId: string) {
    if (expandedId === empId) {
      setExpandedId(null);
      setInvoices([]);
    } else {
      setExpandedId(empId);
      fetchInvoices(empId);
    }
  }

  function openAdd() {
    setEditingId(null);
    setForm(emptyForm);
    setDialogOpen(true);
  }

  function openEdit(emp: Employee) {
    setEditingId(emp.id);
    setForm(formFromEmployee(emp));
    setDialogOpen(true);
  }

  async function handleSave() {
    setSaving(true);

    const payload = {
      name: form.name.trim(),
      cnic: form.cnic.trim() || null,
      default_salary_usd: parseFloat(form.default_salary_usd) || 0,
      default_threshold: parseFloat(form.default_threshold) || 0,
      default_contractor_tax: parseFloat(form.default_contractor_tax) || 0,
      default_remittance_tax: parseFloat(form.default_remittance_tax) || 0,
      is_active: form.is_active,
    };

    if (editingId) {
      await supabase.from("employees").update(payload).eq("id", editingId);
    } else {
      await supabase.from("employees").insert(payload);
    }

    setSaving(false);
    setDialogOpen(false);
    await fetchEmployees();
  }

  async function toggleActive(emp: Employee) {
    await supabase
      .from("employees")
      .update({ is_active: !emp.is_active })
      .eq("id", emp.id);
    await fetchEmployees();
  }

  function updateField(field: keyof EmployeeForm, value: string | boolean) {
    setForm((prev) => ({ ...prev, [field]: value }));
  }

  async function deleteInvoice(inv: InvoiceWithMonth) {
    const confirmed = window.confirm(
      `Delete invoice for ${inv.reference_month} ($${inv.salary_usd})? This deletes the invoice and its linked transactions.`
    );
    if (!confirmed) return;

    try {
      // 1. Delete linked transactions first (FK constraint)
      const { error: txnErr } = await supabase
        .from("transactions")
        .delete()
        .eq("invoice_id", inv.id);
      if (txnErr) console.error("txn delete error:", txnErr);

      // 2. Delete the invoice
      const { error: invErr } = await supabase
        .from("invoices")
        .delete()
        .eq("id", inv.id);
      if (invErr) {
        toast.error(`Failed to delete invoice: ${invErr.message}`);
        return;
      }

      // 3. Check if distribution has any remaining invoices
      const { count } = await supabase
        .from("invoices")
        .select("id", { count: "exact", head: true })
        .eq("distribution_id", inv.distribution_id);

      // 4. If no invoices left, clean up distribution
      if (count === 0) {
        await supabase.from("transactions").delete().eq("distribution_id", inv.distribution_id);
        await supabase.from("distributions").delete().eq("id", inv.distribution_id);
        toast.success("Invoice and empty distribution deleted");
      } else {
        toast.success("Invoice deleted");
      }
    } catch (err) {
      toast.error(`Delete failed: ${err instanceof Error ? err.message : "Unknown error"}`);
    }

    // Refresh
    if (expandedId) fetchInvoices(expandedId);
  }

  const totalEarned = useMemo(
    () => invoices.reduce((s, inv) => s + inv.net_pkr, 0),
    [invoices]
  );

  return (
    <div className="space-y-8">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-semibold tracking-tight">Employees</h1>
        <Button onClick={openAdd}>Add Employee</Button>
      </div>

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>
              {editingId ? "Edit Employee" : "Add Employee"}
            </DialogTitle>
          </DialogHeader>
          <form
            onSubmit={(e) => {
              e.preventDefault();
              handleSave();
            }}
            className="space-y-4"
          >
            <div className="space-y-2">
              <Label htmlFor="name">Name</Label>
              <Input
                id="name"
                value={form.name}
                onChange={(e) => updateField("name", e.target.value)}
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="cnic">CNIC</Label>
              <Input
                id="cnic"
                value={form.cnic}
                onChange={(e) => updateField("cnic", e.target.value)}
                placeholder="XXXXX-XXXXXXX-X"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="salary">Default USD Salary</Label>
                <Input
                  id="salary"
                  type="number"
                  step="any"
                  value={form.default_salary_usd}
                  onChange={(e) =>
                    updateField("default_salary_usd", e.target.value)
                  }
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="threshold">Threshold (PKR)</Label>
                <Input
                  id="threshold"
                  type="number"
                  step="any"
                  value={form.default_threshold}
                  onChange={(e) =>
                    updateField("default_threshold", e.target.value)
                  }
                  required
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="contractor_tax">Contractor Tax %</Label>
                <Input
                  id="contractor_tax"
                  type="number"
                  step="any"
                  value={form.default_contractor_tax}
                  onChange={(e) =>
                    updateField("default_contractor_tax", e.target.value)
                  }
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="remittance_tax">Remittance Tax %</Label>
                <Input
                  id="remittance_tax"
                  type="number"
                  step="any"
                  value={form.default_remittance_tax}
                  onChange={(e) =>
                    updateField("default_remittance_tax", e.target.value)
                  }
                  required
                />
              </div>
            </div>

            <div className="flex items-center gap-2">
              <Checkbox
                id="is_active"
                checked={form.is_active}
                onCheckedChange={(val) => updateField("is_active", !!val)}
              />
              <Label htmlFor="is_active">Active</Label>
            </div>

            <div className="flex justify-end gap-2 pt-2">
              <Button
                type="button"
                variant="outline"
                onClick={() => setDialogOpen(false)}
              >
                Cancel
              </Button>
              <Button type="submit" disabled={saving || !form.name.trim()}>
                {saving ? "Saving..." : editingId ? "Update" : "Add"}
              </Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>

      {loading ? (
        <p className="text-sm text-muted-foreground">Loading...</p>
      ) : employees.length === 0 ? (
        <p className="text-sm text-muted-foreground">
          No employees yet. Add one to get started.
        </p>
      ) : (
        <div className="space-y-3">
          {employees.map((emp) => {
            const isExpanded = expandedId === emp.id;
            return (
              <Card key={emp.id}>
                {/* Employee header row */}
                <div className="flex items-center gap-3 px-4 py-3">
                  <button
                    type="button"
                    className="flex flex-1 items-center gap-3 text-left"
                    onClick={() => toggleExpand(emp.id)}
                  >
                    <ChevronDown
                      className={`size-4 shrink-0 text-muted-foreground transition-transform duration-200 ${
                        isExpanded ? "rotate-180" : ""
                      }`}
                    />
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <span className="font-medium">{emp.name}</span>
                        {!emp.is_active && (
                          <span className="text-xs text-muted-foreground bg-muted px-1.5 py-0.5 rounded">
                            Inactive
                          </span>
                        )}
                      </div>
                      <div className="text-xs text-muted-foreground mt-0.5">
                        {formatUSD(emp.default_salary_usd)}/mo
                        {emp.cnic ? ` · ${emp.cnic}` : ""}
                      </div>
                    </div>
                    <div className="text-right text-xs text-muted-foreground hidden sm:block">
                      <span>Tax: {emp.default_contractor_tax}% + {emp.default_remittance_tax}%</span>
                      <span className="mx-2">·</span>
                      <span>Threshold: {emp.default_threshold}</span>
                    </div>
                  </button>

                  <div className="flex items-center gap-2" onClick={(e) => e.stopPropagation()}>
                    <div className="flex justify-center">
                      <Checkbox
                        checked={emp.is_active}
                        onCheckedChange={() => toggleActive(emp)}
                      />
                    </div>
                    <Button variant="ghost" size="sm" onClick={() => openEdit(emp)}>
                      Edit
                    </Button>
                  </div>
                </div>

                {/* Expanded invoice history */}
                {isExpanded && (
                  <CardContent className="pt-0 border-t border-border/30">
                    <h3 className="text-sm font-semibold mt-3 mb-2">Invoice History</h3>

                    {loadingInvoices ? (
                      <p className="text-sm text-muted-foreground py-2">Loading invoices...</p>
                    ) : invoices.length === 0 ? (
                      <p className="text-sm text-muted-foreground py-2">No invoices yet for this employee.</p>
                    ) : (
                      <>
                        <Table>
                          <TableHeader>
                            <TableRow>
                              <TableHead>Month</TableHead>
                              <TableHead className="text-right">USD</TableHead>
                              <TableHead className="text-right">Rate</TableHead>
                              <TableHead className="text-right">Gross PKR</TableHead>
                              <TableHead className="text-right">Tax</TableHead>
                              <TableHead className="text-right">Net PKR</TableHead>
                              <TableHead className="w-10"></TableHead>
                            </TableRow>
                          </TableHeader>
                          <TableBody>
                            {invoices.map((inv) => (
                              <TableRow key={inv.id}>
                                <TableCell>
                                  {formatMonth(inv.reference_month)}
                                </TableCell>
                                <TableCell className="text-right font-mono">
                                  ${inv.salary_usd}
                                </TableCell>
                                <TableCell className="text-right font-mono">
                                  {formatNumber(inv.rate_applied, 2)}
                                </TableCell>
                                <TableCell className="text-right font-mono">
                                  {formatPKR(inv.gross_pkr)}
                                </TableCell>
                                <TableCell className="text-right font-mono text-red-400">
                                  -{formatPKR(inv.total_tax_pkr)}
                                </TableCell>
                                <TableCell className="text-right font-mono font-semibold text-emerald-400">
                                  {formatPKR(inv.net_pkr)}
                                </TableCell>
                                <TableCell>
                                  <div className="flex items-center gap-1">
                                    <Button
                                      variant="ghost"
                                      size="icon-xs"
                                      onClick={() => printInvoice(inv, emp.name)}
                                      title="Print invoice"
                                    >
                                      <Printer className="size-3.5" />
                                    </Button>
                                    <Button
                                      variant="ghost"
                                      size="icon-xs"
                                      className="text-muted-foreground hover:text-red-400"
                                      onClick={() => deleteInvoice(inv)}
                                      title="Delete invoice"
                                    >
                                      <Trash2 className="size-3.5" />
                                    </Button>
                                  </div>
                                </TableCell>
                              </TableRow>
                            ))}
                          </TableBody>
                        </Table>
                        <div className="flex items-center justify-between mt-3 pt-3 border-t border-border/30 text-sm">
                          <span className="text-muted-foreground">
                            {invoices.length} invoice{invoices.length !== 1 ? "s" : ""}
                          </span>
                          <span className="font-mono font-semibold">
                            Total earned: <span className="text-emerald-400">{formatPKR(totalEarned)}</span>
                          </span>
                        </div>
                      </>
                    )}
                  </CardContent>
                )}
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}
